DEBUG_PLATE_DETECTION = False
DEBUG_PLATE_ROTATION = False
DEBUG_CHARACTER_SEGMENTATION = False
DEBUG_PLATE_CHARACTER_RECOGNITION = False

INPUT_PATH = "Input"

MODEL_WEIGHTS_PATH = "best.pt"
PLATE_DETECTION_CONFIDENCE = 0.2

MIN_PLATE_WIDTH = 100
MIN_PLATE_HEIGHT = 20

MAX_HORIZONTAL_TILT = 20
MAX_VERTICAL_TILT = 13

CHARACTER_WIDTH_MIN = (9 / 520) / 1.3
CHARACTER_WIDTH_MAX = (47 / 520) * 1.3
CHARACTER_HEIGHT_MIN = (72 / 114) / 1.3185
CHARACTER_HEIGHT_MAX = (72 / 114) * 1.3

CHARACTER_ASPECT_RATIO_MIN = (72 / 47) / 1.3
CHARACTER_ASPECT_RATIO_MAX = (72 / 9) * 1.3

CHARACTER_AREA_MIN = ((9 * 72) / (520 * 114)) / 1.65
CHARACTER_AREA_MAX = (((47 * 72) * 0.5) / (520 * 114)) * 1.504

MIN_CHAR_COUNT = 7
MAX_CHAR_COUNT = 8

USE_TESSERACT = True
USE_SYNTAX_ANALISYS = True

TESSRACT_PATH = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
CHARACTER_TEMPLATES_PATH = "Characters"
CHARACTERS_LIST = "0123456789ABCDEFGHIJKLMNOPRSTUVWXYZ"

OCR_CHARACTER_WIDTH = int(47 / 1)
OCR_CHARACTER_HEIGHT = int(80 / 1)

OCR_CONFIDENCE = 0.5

SAVE_DICT_PATH = "Results/"